from __future__ import annotations

import json

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from ..db import get_db
from ..models import UserProfile
from ..schemas import InterviewQuestion, InterviewQuestionsOut, InterviewQuestionsRequest
from ..services.ai_service import AIServiceError
from ..services.taxonomy import canonicalize_skills

router = APIRouter(prefix="/api/interviews", tags=["interviews"])


async def _generate_ai_questions(skills: list[str], count: int) -> list[InterviewQuestion]:
    # lightweight prompt through existing AI pathway (without new provider dependency)
    # raise to fallback if unavailable by policy
    raise AIServiceError("Interview AI endpoint not configured")


@router.post("/questions", response_model=InterviewQuestionsOut)
async def generate_mock_questions(payload: InterviewQuestionsRequest, db: Session = Depends(get_db)):
    profile = db.get(UserProfile, payload.user_profile_id)
    if not profile:
        raise HTTPException(status_code=404, detail={"code": "NOT_FOUND", "message": "Profile not found"})

    profile_skills = canonicalize_skills(json.loads(profile.skills_current_json))
    added = canonicalize_skills(payload.newly_added_skills)
    target_skills = added or profile_skills[:8]

    try:
        questions = await _generate_ai_questions(target_skills, payload.count)
        return InterviewQuestionsOut(generation_mode="ai", questions=questions, notes="Generated by AI interview planner")
    except AIServiceError:
        primary_skill = target_skills[0] if target_skills else "machine learning"
        secondary_skill = target_skills[1] if len(target_skills) > 1 else "python"
        third_skill = target_skills[2] if len(target_skills) > 2 else "sql"

        question_bank: list[InterviewQuestion] = [
            InterviewQuestion(
                question=(
                    f"You are a new-grad SWE building your first {primary_skill} model for churn prediction. "
                    "How would you define the problem, choose a baseline, and measure success?"
                ),
                category="ML Fundamentals",
                difficulty="easy",
            ),
            InterviewQuestion(
                question=(
                    f"Walk through an end-to-end project where you used {secondary_skill} and {third_skill}: "
                    "data ingestion, feature engineering, model training, and deployment checkpoints."
                ),
                category="Applied ML",
                difficulty="medium",
            ),
            InterviewQuestion(
                question=(
                    "Your model has high accuracy but poor recall for a minority class. "
                    "How would you diagnose and improve it?"
                ),
                category="Model Evaluation",
                difficulty="medium",
            ),
            InterviewQuestion(
                question=(
                    "Design a simple offline-to-online ML system for recommending learning resources. "
                    "What components would you include and why?"
                ),
                category="ML System Design",
                difficulty="medium",
            ),
            InterviewQuestion(
                question=(
                    "You discover data leakage after deployment. "
                    "How do you detect impact, roll back safely, and prevent recurrence?"
                ),
                category="Production ML",
                difficulty="hard",
            ),
            InterviewQuestion(
                question=(
                    "For an LLM-powered feature, when would you choose prompt engineering versus fine-tuning? "
                    "Discuss cost, latency, and quality trade-offs."
                ),
                category="Generative AI",
                difficulty="hard",
            ),
            InterviewQuestion(
                question=(
                    "How would you explain model decisions to non-technical stakeholders and build trust in outputs?"
                ),
                category="Communication",
                difficulty="easy",
            ),
            InterviewQuestion(
                question=(
                    "What is your 90-day plan to transition from SWE to ML Engineer while shipping one portfolio project?"
                ),
                category="Career Strategy",
                difficulty="easy",
            ),
        ]

        fallback = question_bank[: payload.count]
        while len(fallback) < payload.count:
            fallback.append(question_bank[len(fallback) % len(question_bank)])

        return InterviewQuestionsOut(
            generation_mode="fallback",
            questions=fallback,
            notes=None,
        )
